doc for workload log anomaly detection (still in progress)
rancher/opni-docs pull request #42
Opened 2022-10-19 02:28 UTC by tybalex

2022-10-19 22:51 UTC, tybalex commented on docs/installation/opni/aiops.md
> +Give it some time for the AI models to get ready. You can then navigate to Opni's Opensearch dashboard and [consume AI Insights](#consume-ai-insights)
here I assume there will be a tab named `consume AI Insights` which describes how user can consume the log anomaly detection AI insights in the Opensearch dashboard, so I simply add a link to it.

2022-10-20 19:41 UTC, sanjay920 approved these changes

2022-10-20 19:42 UTC, sanjay920 requested changes
remove yarn.lock from this PR

2022-10-21 00:26 UTC, sanjay920 approved these changes

2022-10-21 00:27 UTC, merged